---
- name: install pgdg-centos94-9.4-1.noarch.rpm
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=latest

- name: install postgresql and python-psycopg2
  yum: name={{ item }} state=latest
  with_items:
    - postgresql-server
    - postgresql-devel
    - postgresql-contrib
    - python-psycopg2

- name: count file in the data directory
  command: ls /var/lib/pgsql/data
  register: file_count

- name: postgresql initdb
  command: service postgresql initdb
  when: file_count.stdout_lines|length == 0

- name: start postgresql
  service: name=postgresql state=started enabled=yes

- name: create postgres user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    state: present
    login_user: postgres
    role_attr_flags: CREATEDB,LOGIN,SUPERUSER
  sudo_user: postgres

- name: get jpetstore_postgres.sql
  sudo_user: "postgres"
  get_url: url="https://s3-ap-northeast-1.amazonaws.com/dev.cloudconductor.jp/sources/public/jpetstore_postgres.sql" dest=./

- name: create database
  sudo_user: "postgres"
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"

- name: deploy database
  sudo_user: "postgres"
  command: "psql -U postgres -d {{ db_name }} -f jpetstore_postgres.sql"