---
- name: install postgresql
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=latest
  yum: name={{ item }} state=latest
  with_items:
    - postgresql-server
    - postgresql-devel
    - postgresql-contrib
    - python-psycopg2

- name: postgresql initdb
  shell: rm -R /var/lib/pgsql/data/*
  shell: service postgresql initdb

- name: start postgresql
  service: name=postgresql state=started enabled=yes

- name: create postgres user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    state: present
    login_user: postgres
    role_attr_flags: CREATEDB,LOGIN
  sudo_user: postgres

- name: get jpetstore_postgres.sql
  sudo_user: "{{ db_user }}"
  get_url: url="https://s3-ap-northeast-1.amazonaws.com/dev.cloudconductor.jp/sources/public/jpetstore_postgres.sql" dest=./

- name: create database
  sudo_user: "{{ db_user }}"
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"

- name: deploy database
  sudo_user: "{{ db_user }}"
  shell: "psql -U {{ db_user }} -d {{ db_name }} -f jpetstore_postgres.sql"