---
- name: install pgdg-centos94-9.4-1.noarch.rpm
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=present

- name: install postgresql
  yum: name={{ item }} state=latest
  with_items:
    - postgresql-server
    - postgresql-devel
    - postgresql-contrib

- name: install python-psycopg2
  yum: name=python-psycopg2 state=latest

- name: count file in the var/lib/pgsql/data directory
  command: ls /var/lib/pgsql/data
  register: file_count

- name: postgresql initdb
  command: service postgresql initdb
  when: file_count.stdout_lines|length == 0

- name: change pg_hba.conf setting
  template: src=../templates/pg_hba.conf.j2 dest=/var/lib/pgsql/data/pg_hba.conf

- name: start postgresql
  service: name=postgresql state=started enabled=yes

- name: create postgres user
  sudo_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    state: present
    login_user: postgres
    role_attr_flags: CREATEDB,LOGIN,SUPERUSER

- name: get jpetstore_postgres.sql
  sudo_user: "postgres"
  get_url: url="{{ sql_file_url }}" dest=./

- name: create database
  sudo_user: "postgres"
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"

- name: get hostname
  command: hostname
  register: hostname

- name: make .pgpass
  sudo_user: "postgres"
  template: src=../templates/.pgpass.j2 dest=~/.pgpass

- name: chmod .pgpass
  sudo_user: "postgres"
  file: path=~/.pgpass mode=600

- name: deploy database
  sudo_user: "postgres"
  command: "psql -U {{ db_user }} -d {{ db_name }} -f jpetstore_postgres.sql"