---
- name: install apache
  yum: name=httpd state=latest

- name: start httpd
  service: name=httpd state=started enabled=yes

- name: install httpd-devel gcc
  yum: name={{ item }} state=latest
  with_items:
    - httpd-devel
    - gcc

- name: download tomcat-connectors
  get_url: url="http://www.apache.org/dist/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.40-src.tar.gz" dest=./

- name: tar tomcat-connectors
  command: tar -zxvf tomcat-connectors-1.2.40-src.tar.gz

- name: configure tomcat-connectors
  command: ./configure --with-apxs=/usr/bin/apxs chdir=tomcat-connectors-1.2.40-src/native

- name: make tomcat-connectors
  command: make chdir=tomcat-connectors-1.2.40-src/native

- name: make install tomcat-connectors
  command: make install chdir=tomcat-connectors-1.2.40-src/native

- name: copy mod_jk.so
  command: cp apache-2.0/mod_jk.so /etc/httpd/modules/ chdir=tomcat-connectors-1.2.40-src/native

- name: create workers.properties
  template: src=../templates/workers.properties.j2 dest=/etc/httpd/conf.d/workers.properties

- name: create httpd-jk.conf template
  template: src=../templates/httpd-jk.conf.j2 dest=/etc/httpd/conf.d/httpd-jk.conf

- name: restart apache
  service: name=httpd state=restarted