---
- name: tomcat install
  yum: name=tomcat state=latest

- name: application deploy
  get_url: url="https://s3-ap-northeast-1.amazonaws.com/dev.cloudconductor.jp/sources/public/jpetstore.war" dest=/var/lib/tomcat/webapps/

- name: get postgresql jdbc driver
  get_url: url="https://jdbc.postgresql.org/download/postgresql-9.4-1201.jdbc41.jar" dest=/usr/share/tomcat/lib/

- name: tomcat start
  service: name=tomcat state=started enabled=yes

- name: copy jpetstore.xml
  template: src=../templates/jpetstore.xml.j2 dest=/etc/tomcat/Catalina/localhost/jpetstore.xml