---
- name: tomcat install
  yum: name=tomcat state=latest

- name: application deploy
  get_url: url="{{ war_application_url }}" dest=/var/lib/tomcat/webapps/

- name: get postgresql jdbc driver
  get_url: url="{{ jdbc_driver_url }}" dest=/usr/share/tomcat/lib/

- name: tomcat start
  service: name=tomcat state=started enabled=yes

- name: copy jpetstore.xml
  template: src=../templates/jpetstore.xml.j2 dest=/etc/tomcat/Catalina/localhost/jpetstore.xml